name: readest_change
description: A Professional Private Reader Client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  syncfusion_flutter_pdfviewer: ^26.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true